### ISSUE TITLE
Question on running tests

### ISSUE THREAD

**Issue by starunova** [ghost-inspector/node-ghost-inspector#22]
Hello
E.g. I have some module with a number of folders containing scripts launching on demand some tests
how do I launch then entirely(all tests in module) and by folder? I mean with `npm`
Thank you

**Comment by aaronfay** [comment]
Hi @starunova, 

Generally you can drop scripts into your `package.json` file under the `"scripts"` array. Assuming you had a structure that looked like this:

```
.
├── my-gi-tests/
│   ├── my-test.json
│   └── run-my-test.js
└──package.json
```

You could add this to your `package.json` :

```json
{
  "scripts": {
    "gi-test": "node ./my-gi-tests/run-my-test.js"
  }
}
```



And then execute that like this:

```sh
npm run gi-test
```

To run all of the tests at once will probably require some kind of wrapper (instead of the `./my-gi-tests/run-my-test.js` script) but some experimentation may be required to get the results you're looking for.

Hope that helps you get going! 👋🏻
